### PR TITLE
Enable Self Hosted Encoder Remove/Comment Rewrite (Errors Loading YouPHPTube)

### PR DESCRIPTION
**Pull request by ghost**
apache.conf added for sole purpose of AllowOverride All, shown below required for Encoder. Had encoder listen on 81 and 445 to facilitate use of IP address or domain during installation and for the sake of simplicity in only specifying one domain during initial setup.

<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride All
	Require all granted
</Directory>

Everything else is additions to enable the encoder and set the default encoder to the self hosted encoder instead of the public encoder.

When testing initial connection between YouPHPTube and YouPHPTube encoder takes about 30 seconds to initiate.

If you are curious about the plain text password saved in YouPHPTube Encoder please reference this:
https://github.com/DanielnetoDotCom/YouPHPTube/issues/834
I inquired about the issue and the maintainers of YouPHPTube are aware and will be fixing the issue at some point in the future. It is what it is for now.

### CODE REVIEW

**Comment by JedMeister** [comment]
Hey @MPTMG 

Ok, I've just cherry picked the 2 commits from this pull request which seem to provide all the required changes to support encoding (https://github.com/turnkeylinux-apps/youphptube/commit/eb997d17abb01d7e9f3816d9cac9d8d5bd2839de & https://github.com/turnkeylinux-apps/youphptube/commit/fe9f4736c504979f670403431f332778eb148142). Please let me know if I'm missing anything.

I've also made a few modifications, namely:
- modifying the existing apache2/ports.conf (rather than overwriting via an overlay) - https://github.com/turnkeylinux-apps/youphptube/commit/250aecde6c8c48f35e2646a6b734dba66cfd05a8
- also removed the apache.conf overlay and adjusted the overlaid apache conf files https://github.com/turnkeylinux-apps/youphptube/commit/a39a50082c969023a7f51464c9d6cc8c8ed9a816 (better to leave the defaults and adjust what we need to). Hopefully my changes give the required effect.

I'm also pretty sure that I've fixed the browser redirect loop issue. Now it should still redirect from http to https but shouldn't choke if an IP address is used instead of a domain - https://github.com/turnkeylinux-apps/youphptube/commit/5b073501aa0cfcfda7ceeabe036c2847622eb17f

I've tested the changes in a YouPHPTube v15.0 appliance I have running locally, and all seems good. Plus I am just about to put the updated appliance code on to build. But I need to get on with some other quite urgent stuff so if you get a chance to test, that'd be awesome. I've pushed my latest commits to a new branch of the turnkey repo called "mptmg-encoding-addition" ([here](https://github.com/turnkeylinux-apps/youphptube/tree/mptmg-encoding-addition)).

Totally open to further feedback on this/these.

**Comment by ghost** [comment]
I will test tomorrow morning.

**Comment by ghost** [comment]
@JedMeister. Cloned and built the mptmg-encoding-addition branch. Build is fully functional and the redirect is indeed fixed and functional in both use cases(IP or Domain). Tested all functions upload, import video link, watch, live stream, view live stream, and encode. Glad to see the encoding getting integrated.

Outstanding simple changes to get rid of the apache.conf in overlay as well as simple sed to add the required lines to ports.conf. (Wish I would have done it this way).

**Comment by JedMeister** [comment]
I'm going to close this pull request as I'm 99% sure I have everything included already (between cherry picking some of your commits and a few commits I did). v15.1 has now been released.

If there is anything missing, please feel free to open an issue and/or open a new pull request.

**Pull request closed without merging**
